theme: minima
title: My awesome webpage using github
author: Cody Diane Hackney

description: > # this means to ignore newlines until "baseurl:"
Hello this is my first time makeing a webpage using GitHub..

# social links

github_username:  chackney0

show_excerpts: true # set to false to remove excerpts on the homepage
